apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: k8api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000  
      targetPort: 8000
      nodePort: 32000