apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-variables
data:
  #env variables for the postgres component
  POSTGRES_DB: testdb
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres-service
  
