apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: k8sweb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000  
      targetPort: 3000
      nodePort: 31000