apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8sweb
  template:
    metadata:
      labels:
        app: k8sweb
    spec:
      containers:
      - name: k8sweb
        image: khanjanmarthak/kubernetesweb
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: LOGIN_API
            valueFrom:
              secretKeyRef:
                name: k8secrets
                key: LOGIN_API


              
        ports:
        - containerPort: 3000

